"""rename department

Revision ID: ba946cee8d10
Revises: dba441469458
Create Date: 2024-05-30 19:46:29.687927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba946cee8d10'
down_revision = 'dba441469458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')

    # ### end Alembic commands ###
